@echo off
echo [1/3] Pulling latest code...
git pull

echo [2/3] Installing dependencies...
call npm install

echo [3/3] Building production application...
call npm run build

echo [4/4] Bouncing Windows Service...
nssm restart CreaPanel